### ISSUE TITLE
Start the demo

### ISSUE THREAD

**Issue by likeconan** [domagojk/beenion#3]
Hi,

I am new to typescript and ddd.

I really want to start to learn about your design pattern.

Anyway the problem is that I want to make the project run but got some error.

Could you help with README so that I can run the project successful?

Thanks

**Comment by domagojk** [comment]
Hi,

Unfortunately there isn't much to run right now. This is more a showcase on
how an architecuture like this can be set up.
I have mostly used this patterns in projects which are under contracts, so
i cant publish them publicly..

But, if i find time i think i will soon finish a new version of beenion
which would be a service that you can use


pon, 23. srp 2018. 02:39 likeconan <notifications@github.com> je napisao:
