### ISSUE TITLE
rebuildDatabase.ts usage

### ISSUE THREAD

**Issue by herebebogans** [domagojk/beenion#6]
Do you have any guidance on how `rebuildDatabase.ts` can be used / invoked to recreate the Link table from the EventStore?

**Comment by herebebogans** [comment]
I worked this out - closing.

**Comment by domagojk** [comment]
@herebebogans You reminded me that I should update that function and getByTimestamp implementation. So if you need it, I advise you to see how it works now.

It seems the last implementation had some strange racing condition issues which occurred when working on a large number of events (I discovered them in a separate project).

`rebuildDatabase.ts` now looks a bit more complex but all you need is on line 14.
